name: Build & Release Launcher (Windows)
on:
  push:
    tags: ["launcher-v*"]  # e.g., launcher-v0.1.0

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write   # needed to create a release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build deps
        run: pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: pyinstaller --noconfirm --onefile --windowed -n SilhouetteLauncher launcher/main.py

      - name: Upload as CI artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: SilhouetteLauncher
          path: dist/SilhouetteLauncher.exe

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SilhouetteLauncher.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
