target-version = "py310"
line-length = 100
exclude = [
  ".venv","venv","build","dist",
  "artifacts","scripts/__pycache__","tests/fixtures",
]

[lint]
select = ["E","F","I","B","UP","SIM"]
ignore = ["E203","E501"]

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"tests/**" = ["S101"]
