model:
  name: TinyLlama/TinyLlama-1.1B-Chat-v1.0
  max_new_tokens: 256
  temperature: 0.7
  top_p: 0.9

alignment:
  persona_dsl: docs/alignment_kernel/persona.dsl
  deny_on_default_message: "I'm not permitted to assist with that request."

runtime:
  offline_fallback: deterministic
  log_json: false
