# Lane test pass thresholds (min passed / total)
lanes:
  basics:   { min_pass_rate: 1.00 }
  python:   { min_pass_rate: 0.80 }
  web:      { min_pass_rate: 0.80 }
  java:     { min_pass_rate: 0.75 }
  dotnet:   { min_pass_rate: 0.75 }
  android:  { min_pass_rate: 0.60 }
  cpp:      { min_pass_rate: 0.70 }

# Latency p50 (seconds) budgets
latency:
  selfcheck_p50: { max: 1.0, tolerance_pct: 10 }
  short_answer_p50: { max: 3.0, tolerance_pct: 10 }

# Flake / quarantine controls
quarantine:
  tests: []
  lanes: []

# Regression sensitivity (trend against previous snapshot)
regression:
  fail_on_drop_pct: 5
  require_baseline: false
