mrn: http://example.org/mrn
visit: http://example.org/visit
order: http://example.org/order
specimen: http://example.org/specimen
organization: http://example.org/organization
practitioner: http://example.org/practitioner
location: http://example.org/location
