name: CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install ruff pytest

      - name: Lint
        run: ruff check silhouette_core tests

      - name: Unit tests (auto-skip optional suites)
        run: pytest -q

      - name: Security scan (core)
        run: >
          python -m silhouette_core.security.scanner
          --path silhouette_core
          --out artifacts/security_core.json
          --license_whitelist "MIT,Apache-2.0,BSD-2-Clause,BSD-3-Clause,Proprietary,LicenseRef-Silhouette-Internal"
          --license_denylist "GPL-3.0,AGPL-3.0,MPL-2.0"
          --max_high 0 --max_medium 200 --max_low 2000

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: artifacts/**

