# .github/workflows/ci.yml
name: Silhouette Core CI

on:
  push:
    branches:
      - main
      - staging
      - 'train/**'
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-test-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # pydantic v1 compatibility for fhir.resources 7.x
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Lint (non-blocking)
        run: ruff check . || true

      - name: Run tests
        run: pytest -q --maxfail=1 --durations=10

      - name: Set up Node (for Mermaid export)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Export Mermaid diagrams (best-effort)
        run: |
          npm i -g @mermaid-js/mermaid-cli || true
          python scripts/export_mermaid.py docs/ || true

      - name: Build Profile Conformance Report (best-effort)
        run: python scripts/profile_conformance.py || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: silhouette-reports
          path: |
            reports/
            docs/**/svg/*.svg
            logs/
