name: Codex On-Demand Tests

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  run-tests:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       startsWith(github.event.comment.body, '/codex test'))
    runs-on: ubuntu-latest

    steps:
      - name: Determine PR ref (when triggered by comment)
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            if (context.eventName !== 'issue_comment') {
              core.setOutput('ref', context.sha);
              return;
            }
            const prUrl = context.payload.issue.pull_request.url;
            const pr = await github.request(`GET ${prUrl}`);
            core.setOutput('ref', pr.data.head.sha);

      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lint (non-blocking)
        run: ruff check . || true

      - name: Run tests
        run: pytest -q --maxfail=1 --durations=10

      - name: Build Profile Conformance Report
        run: python scripts/profile_conformance.py || true

      - name: Export Mermaid diagrams (non-fatal if Node missing)
        run: |
          set -e
          npm i -g @mermaid-js/mermaid-cli || exit 0
          python scripts/export_mermaid.py docs/ || true

      - name: Upload reports & logs
        uses: actions/upload-artifact@v4
        with:
          name: silhouette-reports
          path:
            - reports/
            - docs/**/svg/*.svg
            - logs/
          if-no-files-found: warn
