name: Nightly Interop E2E

on:
  schedule:
    - cron: "23 7 * * *"
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: E2E-focused tests
        run: pytest -q -k "end_to_end or draft_and_sender or mllp" --maxfail=1

      - name: Conformance & artifacts
        run: |
          python scripts/profile_conformance.py || true

      - uses: actions/upload-artifact@v4
        with:
          name: nightly-reports
          path: reports/
