name: Train Reasoner

on:
  push:
    branches: [main, 'train/*']

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install accelerate huggingface_hub

      - name: Generate teacher outputs
        run: python teacher_generate_multi.py
      - name: Merge teacher outputs
        run: python silhouette_core/merge_teacher_outputs.py
      - name: Evaluate student
        run: python evaluate_student.py
      - name: Train adapter
        run: python train_adapter.py
      - name: Quantize models
        run: python quantize_models.py
      - name: Upload adapter
        uses: actions/upload-artifact@v4
        with:
          name: reasoner-adapter
          path: modules/reasoner/adapter/qlora4b
