name: Train Reasoner

on:
  push:
    paths:
      - 'modules/reasoner/**'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Generate teacher outputs
        run: python teacher_generate_multi.py
      - name: Merge teacher outputs
        run: python silhouette_core/merge_teacher_outputs.py
      - name: Evaluate student
        run: python evaluate_student.py
      - name: Train adapter
        run: python train_adapter.py
      - name: Quantize models
        run: python quantize_models.py
      - name: Upload adapter
        uses: actions/upload-artifact@v4
        with:
          name: reasoner-adapter
          path: modules/reasoner/adapter/qlora4b
